# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

"""
 
author: Skyler Sun
create date: 2022-12-05 Monday
weather: small rain
script name: download.py

"""

import sys
import subprocess
import webbrowser
import tkinter as tk
import re
from tkinter.messagebox import showerror,showinfo,showwarning
from PyQt5 import QtCore, QtGui, QtWidgets

from win_setting import SettingWindow
from download import Bilibili, CloudMusic
from query import query_config


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.folderPath = query_config('config/settings.json')['save_path']
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(481, 240)
        MainWindow.setMinimumSize(QtCore.QSize(10, 10))
        MainWindow.setMaximumSize(QtCore.QSize(9999, 9999))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.VideoLabel = QtWidgets.QLabel(self.centralwidget)
        self.VideoLabel.setGeometry(QtCore.QRect(10, 30, 101, 51))
        self.VideoLabel.setObjectName("VideoLabel")
        self.DownloadVideoButton = QtWidgets.QPushButton(self.centralwidget)
        self.DownloadVideoButton.setGeometry(QtCore.QRect(380, 30, 81, 31))
        self.DownloadVideoButton.setObjectName("DownloadVideoButton")
        self.MusicLabel = QtWidgets.QLabel(self.centralwidget)
        self.MusicLabel.setGeometry(QtCore.QRect(10, 120, 101, 51))
        self.MusicLabel.setObjectName("MusicLabel")
        self.DownloadMusicButton = QtWidgets.QPushButton(self.centralwidget)
        self.DownloadMusicButton.setGeometry(QtCore.QRect(380, 120, 81, 31))
        self.DownloadMusicButton.setObjectName("DownloadMusicButton")
        self.VideoLinkInput = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.VideoLinkInput.setGeometry(QtCore.QRect(130, 20, 231, 71))
        self.VideoLinkInput.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.VideoLinkInput.setObjectName("VideoLinkInput")
        self.MusicLinkInput = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.MusicLinkInput.setGeometry(QtCore.QRect(130, 110, 231, 71))
        self.MusicLinkInput.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.MusicLinkInput.setObjectName("MusicLinkInput")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 481, 23))
        self.menubar.setObjectName("menubar")
        self.MenuSettings = QtWidgets.QMenu(self.menubar)
        self.MenuSettings.setToolTipsVisible(False)
        self.MenuSettings.setObjectName("MenuSettings")
        self.MenuHelp = QtWidgets.QMenu(self.menubar)
        self.MenuHelp.setObjectName("MenuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.ActionAbout = QtWidgets.QAction(MainWindow)
        self.ActionAbout.setObjectName("ActionAbout")
        self.ActionSettingDashborad = QtWidgets.QAction(MainWindow)
        self.ActionSettingDashborad.setIconVisibleInMenu(True)
        self.ActionSettingDashborad.setShortcutVisibleInContextMenu(True)
        self.ActionSettingDashborad.setObjectName("ActionSettingDashborad")
        self.ActionAddress = QtWidgets.QAction(MainWindow)
        self.ActionAddress.setObjectName("ActionAddress")
        self.ActionUpdateApi = QtWidgets.QAction(MainWindow)
        self.ActionUpdateApi.setObjectName("ActionUpdateApi")
        self.MenuSettings.addAction(self.ActionSettingDashborad)
        self.MenuSettings.addAction(self.ActionUpdateApi)
        self.MenuHelp.addAction(self.ActionAddress)
        self.MenuHelp.addSeparator()
        self.MenuHelp.addAction(self.ActionAbout)
        self.menubar.addAction(self.MenuSettings.menuAction())
        self.menubar.addAction(self.MenuHelp.menuAction())

        # 设置默认显示文字
        self.VideoLinkInput.appendPlainText('在此处输入对应链接(输入时请删除本提示文字)')
        self.MusicLinkInput.appendPlainText('在此处输入对应链接(输入时请删除本提示文字)')
        # 信号连接
        self.ActionAbout.triggered.connect(self.about)
        self.ActionAddress.triggered.connect(self.about)
        self.ActionSettingDashborad.triggered.connect(self.setting)
        self.ActionUpdateApi.triggered.connect(self.update_own)
        self.DownloadMusicButton.clicked.connect(self.D_music)
        self.DownloadVideoButton.clicked.connect(self.D_video)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sk Getter"))
        self.VideoLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">下载视频</span></p></body></html>"))
        self.DownloadVideoButton.setText(_translate("MainWindow", "开始下载"))
        self.MusicLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">下载歌曲</span></p></body></html>"))
        self.DownloadMusicButton.setText(_translate("MainWindow", "开始下载"))
        self.MenuSettings.setTitle(_translate("MainWindow", "设置"))
        self.MenuHelp.setTitle(_translate("MainWindow", "帮助"))
        self.ActionAbout.setText(_translate("MainWindow", "关于"))
        self.ActionSettingDashborad.setText(_translate("MainWindow", "全局设置"))
        self.ActionAddress.setText(_translate("MainWindow", "源码地址"))
        self.ActionUpdateApi.setText(_translate("MainWindow", "更新软件"))

    def about(self):
        """打开浏览器访问主页"""
        url = 'https://gitee.com/skyler-sun/sk-getter'
        webbrowser.open(url)

    def setting(self):
        """打开设置窗口"""
        SettingWindow.show()

    def update_own(self):
        """更新软件"""
        #TODO:更新软件
        pass

    def D_music(self):
        """下载音乐"""
        self.musicUrl = self.MusicLinkInput.toPlainText()
        if self.musicUrl == '':
            root = tk.Tk()
            root.withdraw()
            root.iconbitmap('img/icon.ico')
            showwarning('警告', '歌曲链接不能为空')
            root.quit()
        if re.match('https://music.163.com', self.musicUrl) != None:
            # 判断为网易云音乐链接
            self.musicID = re.findall('.*?id=(.*)', self.musicUrl)
            downloader = CloudMusic(self.musicID)
            downloader.download(self.folderPath)
            self.open_save()
    
    def open_save(self):
        """打开保存位置"""
        self.folderPath = self.folderPath.replace('/', '\\')
        subprocess.Popen(f'explorer.exe {self.folderPath}')
    
    def D_video(self):
        """下载视频"""
        self.videoUrl = self.VideoLinkInput.toPlainText()
        if self.videoUrl == '':
            root = tk.Tk()
            root.withdraw()
            root.iconbitmap('img/icon.ico')
            showwarning('警告', '视频链接不能为空')
            root.quit()
        if re.match('https://www.bilibili.com', self.videoUrl) != None:
            # 判断为bilibili链接
            downloader = Bilibili(self.videoUrl)
            self.urls = downloader.get_one_link()
            if self.urls != None:
                root = tk.Tk()
                root.withdraw()
                root.iconbitmap('img/icon.ico')
                tips = "下载已经开始,B站默认下载最高画质,更高画质需要登录(目前功能尚未实现),下载完成后会自动打开文件夹,文件名经过md5加密(看起来像乱码的mp4),请勿多次重复点击下载按钮"
                showinfo('INFO', tips)
                downloader.download(self.urls['video_url'], 'a.mp4')
                downloader.download(self.urls['audio_url'], 'b.mp3')
                self.videoName = downloader.get_name()
                downloader.merge(f'{self.videoName}.mp4')
                self.open_save()

app = QtWidgets.QApplication(sys.argv)
MainWindow = QtWidgets.QMainWindow()
with open('style.qss') as f:
    style = f.read()
MainWindow.setStyleSheet(style)
ui = Ui_MainWindow()
ui.setupUi(MainWindow)
